# Generated by Django 3.2.25 on 2024-07-22 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.URLField(blank=True, null=True)),
                ('target', models.URLField(blank=True, null=True)),
                ('swapped', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
